[package]
name = "memorun"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "memorun"
path = "src/main.rs"

[dependencies]
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
thiserror = "2.0.18"
tokio = { version = "1.52.2", features = ["tokio-macros"] }
